name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

 

    - name: Building the installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "FreenetInstall_InnoSetup.iss"
      shell: cmd

    - name: Sign the installer
      uses: nextgens/authenticode-sign-action@v1.0.1
      if: ${{ github.event_name != 'pull_request' }}
      with:
        certificate: '${{ secrets.CERTIFICATES }}'
        credentials: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
        key-uri: "projects/fpi-codesign/locations/europe-west3/keyRings/code-signing/cryptoKeys/certificate/cryptoKeyVersions/1"
        timestamp-url: 'http://timestamp.comodoca.com'
        description: 'Freenet Installer'
        description-url: 'https://freenetproject.org'
        folder: "Output"
        recursive: true

    - name: Verify the signature
      if: ${{ github.event_name != 'pull_request' }}
      run: call "%programfiles(x86)%/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe" verify /v /pa "Output/FreenetInstaller.exe"
      shell: cmd

    - name: Upload the installer as an artifact
      uses: actions/upload-artifact@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        path: "Output/FreenetInstaller.exe"
        name: wininstaller-innosetup

